DefaultContentLanguage = "en"
author = "Zambo"
baseURL = "https://zambo.netlify.com/"
copyright = "Copyright © Whenever; all rights reserved."
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
languageCode = "en"
paginate = 3
theme = "casper3"
title = "Zambo Thoughts"
[[menu.main]]
identifier = "author"
name = "Author Homepage"
url = "https://zambo.netlify.com"
weight = 2
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1
[params]
description = "Where I ponder on how the world works."
facebook = "https://facebook.com"
github = ""
mainSections = ["post"]
twitter = "https://twitter.com"
[privacy.instagram]
disabled = false
simple = true
[privacy.twitter]
disabled = false
enableDNT = true
simple = true
[privacy.vimeo]
disabled = false
simple = true
[privacy.youtube]
disabled = false
privacyEnhanced = true
[services.instagram]
disableInlineCSS = true
[services.twitter]
disableInlineCSS = true
[taxonomies]
category = "categories"
series = "series"
tag = "tags"
